// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Whatever you put in this `FileTop` section will end up 
// being printed at the top of every generated code file.

#pragma once  // You can also specify normal include guard. See https://github.com/StateSmith/StateSmith/blob/main/docs/settings.md
#include <stdint.h>
#include <stdint.h> // for count var



typedef enum MyTraffic_EventId
{
    MyTraffic_EventId_REQUESTGREEN = 0,
    MyTraffic_EventId_TICK = 1
} MyTraffic_EventId;

enum
{
    MyTraffic_EventIdCount = 2
};

typedef enum MyTraffic_StateId
{
    MyTraffic_StateId_ROOT = 0,
    MyTraffic_StateId_TRAFFICLIGHTGREEN = 1,
    MyTraffic_StateId_TRAFFICLIGHTSTATERED = 2,
    MyTraffic_StateId_TRAFFICLIGHTSTATEREDYELLOW = 3,
    MyTraffic_StateId_TRAFFICLIGHTYELLOW = 4,
    MyTraffic_StateId_YELLOWOFF = 5,
    MyTraffic_StateId_YELLOWON = 6
} MyTraffic_StateId;

enum
{
    MyTraffic_StateIdCount = 7
};


// Generated state machine
// forward declaration
typedef struct MyTraffic MyTraffic;

// State machine variables. Can be used for inputs, outputs, user variables...
typedef struct MyTraffic_Vars
{
    uint16_t count; // this var can be referenced in diagram
} MyTraffic_Vars;


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void MyTraffic_ctor(MyTraffic* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void MyTraffic_start(MyTraffic* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void MyTraffic_dispatch_event(MyTraffic* sm, MyTraffic_EventId event_id);

// Thread safe.
char const * MyTraffic_state_id_to_string(MyTraffic_StateId id);

// Thread safe.
char const * MyTraffic_event_id_to_string(MyTraffic_EventId id);

// Generated state machine
struct MyTraffic
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    MyTraffic_StateId state_id;
    
    // Variables. Can be used for inputs, outputs, user variables...
    MyTraffic_Vars vars;
};

