// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Whatever you put in this `FileTop` section will end up 
// being printed at the top of every generated code file.

#include "MyTraffic.hpp"
#include "Actions.hpp" // for action implementations
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset
// #include "your_header_here.h"


// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(MyTraffic* sm, MyTraffic_StateId desired_state);

static void ROOT_enter(MyTraffic* sm);

static void TRAFFICLIGHTGREEN_enter(MyTraffic* sm);

static void TRAFFICLIGHTGREEN_exit(MyTraffic* sm);

static void TRAFFICLIGHTGREEN_tick(MyTraffic* sm);

static void TRAFFICLIGHTSTATERED_enter(MyTraffic* sm);

static void TRAFFICLIGHTSTATERED_exit(MyTraffic* sm);

static void TRAFFICLIGHTSTATERED_requestgreen(MyTraffic* sm);

static void TRAFFICLIGHTSTATERED_tick(MyTraffic* sm);

static void TRAFFICLIGHTSTATEREDYELLOW_enter(MyTraffic* sm);

static void TRAFFICLIGHTSTATEREDYELLOW_exit(MyTraffic* sm);

static void TRAFFICLIGHTSTATEREDYELLOW_tick(MyTraffic* sm);

static void TRAFFICLIGHTYELLOW_enter(MyTraffic* sm);

static void TRAFFICLIGHTYELLOW_exit(MyTraffic* sm);

static void TRAFFICLIGHTYELLOW_tick(MyTraffic* sm);

static void YELLOWOFF_enter(MyTraffic* sm);

static void YELLOWOFF_exit(MyTraffic* sm);

static void YELLOWOFF_tick(MyTraffic* sm);

static void YELLOWON_enter(MyTraffic* sm);

static void YELLOWON_exit(MyTraffic* sm);

static void YELLOWON_tick(MyTraffic* sm);

uint32_t timer; // Global variable to track time in states


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void MyTraffic_ctor(MyTraffic* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void MyTraffic_start(MyTraffic* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: / { initRedLight(); initYellowLight(); initGreenLight() } TransitionTo(TrafficLightStateRed)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: `initRedLight(); initYellowLight(); initGreenLight()`.
            initRedLight(); initYellowLight(); initGreenLight();
            
            // Step 3: Enter/move towards transition target `TrafficLightStateRed`.
            TRAFFICLIGHTSTATERED_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void MyTraffic_dispatch_event(MyTraffic* sm, MyTraffic_EventId event_id)
{
    switch (sm->state_id)
    {
        // STATE: MyTraffic
        case MyTraffic_StateId_ROOT:
            // No events handled by this state (or its ancestors).
            break;
        
        // STATE: TrafficLightGreen
        case MyTraffic_StateId_TRAFFICLIGHTGREEN:
            switch (event_id)
            {
                case MyTraffic_EventId_TICK: TRAFFICLIGHTGREEN_tick(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: TrafficLightStateRed
        case MyTraffic_StateId_TRAFFICLIGHTSTATERED:
            switch (event_id)
            {
                case MyTraffic_EventId_TICK: TRAFFICLIGHTSTATERED_tick(sm); break;
                case MyTraffic_EventId_REQUESTGREEN: TRAFFICLIGHTSTATERED_requestgreen(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: TrafficLightStateRedYellow
        case MyTraffic_StateId_TRAFFICLIGHTSTATEREDYELLOW:
            switch (event_id)
            {
                case MyTraffic_EventId_TICK: TRAFFICLIGHTSTATEREDYELLOW_tick(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: TrafficLightYellow
        case MyTraffic_StateId_TRAFFICLIGHTYELLOW:
            switch (event_id)
            {
                case MyTraffic_EventId_TICK: TRAFFICLIGHTYELLOW_tick(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: YellowOff
        case MyTraffic_StateId_YELLOWOFF:
            switch (event_id)
            {
                case MyTraffic_EventId_TICK: YELLOWOFF_tick(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: YellowOn
        case MyTraffic_StateId_YELLOWON:
            switch (event_id)
            {
                case MyTraffic_EventId_TICK: YELLOWON_tick(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(MyTraffic* sm, MyTraffic_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case MyTraffic_StateId_TRAFFICLIGHTGREEN: TRAFFICLIGHTGREEN_exit(sm); break;
            
            case MyTraffic_StateId_TRAFFICLIGHTSTATERED: TRAFFICLIGHTSTATERED_exit(sm); break;
            
            case MyTraffic_StateId_TRAFFICLIGHTSTATEREDYELLOW: TRAFFICLIGHTSTATEREDYELLOW_exit(sm); break;
            
            case MyTraffic_StateId_TRAFFICLIGHTYELLOW: TRAFFICLIGHTYELLOW_exit(sm); break;
            
            case MyTraffic_StateId_YELLOWOFF: YELLOWOFF_exit(sm); break;
            
            case MyTraffic_StateId_YELLOWON: YELLOWON_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(MyTraffic* sm)
{
    sm->state_id = MyTraffic_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRAFFICLIGHTGREEN
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICLIGHTGREEN_enter(MyTraffic* sm)
{
    sm->state_id = MyTraffic_StateId_TRAFFICLIGHTGREEN;
    
    // TrafficLightGreen behavior
    // uml: enter / { turnOnGreenLight(), timer = 0 }
    {
        // Step 1: execute action `turnOnGreenLight(), timer = 0`
        turnOnGreenLight(), timer = 0;

        requestGreen = false; // reset requestGreen variable
        updateLedMode(sm); // Update mode LEDs
    } // end of behavior for TrafficLightGreen
}

static void TRAFFICLIGHTGREEN_exit(MyTraffic* sm)
{
    // TrafficLightGreen behavior
    // uml: exit / { turnOffGreenLight() }
    {
        // Step 1: execute action `turnOffGreenLight()`
        turnOffGreenLight();
    } // end of behavior for TrafficLightGreen
    
    sm->state_id = MyTraffic_StateId_ROOT;
}

static void TRAFFICLIGHTGREEN_tick(MyTraffic* sm)
{
    // TrafficLightGreen behavior
    // uml: tick / { timer++ }
    {
        // Step 1: execute action `timer++`
        timer++;
    } // end of behavior for TrafficLightGreen
    
    // TrafficLightGreen behavior
    // uml: tick [timer > greenTime] TransitionTo(TrafficLightYellow)
    if (timer > greenTime)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTGREEN_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightYellow`.
        TRAFFICLIGHTYELLOW_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightGreen
    
    // TrafficLightGreen behavior
    // uml: tick [light < thresholdNight] TransitionTo(YellowOn)
    if (light < thresholdNight)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTGREEN_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `YellowOn`.
        YELLOWON_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightGreen
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRAFFICLIGHTSTATERED
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICLIGHTSTATERED_enter(MyTraffic* sm)
{
    sm->state_id = MyTraffic_StateId_TRAFFICLIGHTSTATERED;
    
    // TrafficLightStateRed behavior
    // uml: enter / { turnOnRedLight(), timer = 0 }
    {
        // Step 1: execute action `turnOnRedLight(), timer = 0`
        turnOnRedLight(), timer = 0;
    } // end of behavior for TrafficLightStateRed
}

static void TRAFFICLIGHTSTATERED_exit(MyTraffic* sm)
{
    // TrafficLightStateRed behavior
    // uml: exit / { turnOffRedLight() }
    {
        // Step 1: execute action `turnOffRedLight()`
        turnOffRedLight();
    } // end of behavior for TrafficLightStateRed
    
    sm->state_id = MyTraffic_StateId_ROOT;
}

static void TRAFFICLIGHTSTATERED_requestgreen(MyTraffic* sm)
{
    // TrafficLightStateRed behavior
    // uml: requestGreen TransitionTo(TrafficLightStateRedYellow)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTSTATERED_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightStateRedYellow`.
        TRAFFICLIGHTSTATEREDYELLOW_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightStateRed
    
    // No ancestor handles this event.
}

static void TRAFFICLIGHTSTATERED_tick(MyTraffic* sm)
{
    // TrafficLightStateRed behavior
    // uml: tick / { timer++ }
    {
        // Step 1: execute action `timer++`
        timer++;
    } // end of behavior for TrafficLightStateRed
    
    // TrafficLightStateRed behavior
    // uml: tick [light < thresholdNight] TransitionTo(YellowOn)
    if (light < thresholdNight)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTSTATERED_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `YellowOn`.
        YELLOWON_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightStateRed
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRAFFICLIGHTSTATEREDYELLOW
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICLIGHTSTATEREDYELLOW_enter(MyTraffic* sm)
{
    sm->state_id = MyTraffic_StateId_TRAFFICLIGHTSTATEREDYELLOW;
    
    // TrafficLightStateRedYellow behavior
    // uml: enter / { turnOnRedLight(), turnOnYellowLight(), timer = 0 }
    {
        // Step 1: execute action `turnOnRedLight(), turnOnYellowLight(), timer = 0`
        turnOnRedLight(), turnOnYellowLight(), timer = 0;
    } // end of behavior for TrafficLightStateRedYellow
}

static void TRAFFICLIGHTSTATEREDYELLOW_exit(MyTraffic* sm)
{
    // TrafficLightStateRedYellow behavior
    // uml: exit / { turnOffRedLight(), turnOffYellowLight() }
    {
        // Step 1: execute action `turnOffRedLight(), turnOffYellowLight()`
        turnOffRedLight(), turnOffYellowLight();
    } // end of behavior for TrafficLightStateRedYellow
    
    sm->state_id = MyTraffic_StateId_ROOT;
}

static void TRAFFICLIGHTSTATEREDYELLOW_tick(MyTraffic* sm)
{
    // TrafficLightStateRedYellow behavior
    // uml: tick / { timer++ }
    {
        // Step 1: execute action `timer++`
        timer++;
    } // end of behavior for TrafficLightStateRedYellow
    
    // TrafficLightStateRedYellow behavior
    // uml: tick [timer > 2000] TransitionTo(TrafficLightGreen)
    if (timer > 2000)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTSTATEREDYELLOW_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightGreen`.
        TRAFFICLIGHTGREEN_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightStateRedYellow
    
    // TrafficLightStateRedYellow behavior
    // uml: tick [light < thresholdNight] TransitionTo(YellowOn)
    if (light < thresholdNight)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTSTATEREDYELLOW_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `YellowOn`.
        YELLOWON_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightStateRedYellow
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRAFFICLIGHTYELLOW
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICLIGHTYELLOW_enter(MyTraffic* sm)
{
    sm->state_id = MyTraffic_StateId_TRAFFICLIGHTYELLOW;
    
    // TrafficLightYellow behavior
    // uml: enter / { turnOnYellowLight(), timer = 0 }
    {
        // Step 1: execute action `turnOnYellowLight(), timer = 0`
        turnOnYellowLight(), timer = 0;
    } // end of behavior for TrafficLightYellow
}

static void TRAFFICLIGHTYELLOW_exit(MyTraffic* sm)
{
    // TrafficLightYellow behavior
    // uml: exit / { turnOffYellowLight() }
    {
        // Step 1: execute action `turnOffYellowLight()`
        turnOffYellowLight();
    } // end of behavior for TrafficLightYellow
    
    sm->state_id = MyTraffic_StateId_ROOT;
}

static void TRAFFICLIGHTYELLOW_tick(MyTraffic* sm)
{
    // TrafficLightYellow behavior
    // uml: tick / { timer++ }
    {
        // Step 1: execute action `timer++`
        timer++;
    } // end of behavior for TrafficLightYellow
    
    // TrafficLightYellow behavior
    // uml: tick [time > 3000] TransitionTo(TrafficLightStateRed)
    if (timer > 3000)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTYELLOW_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightStateRed`.
        TRAFFICLIGHTSTATERED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightYellow
    
    // TrafficLightYellow behavior
    // uml: tick [light < thresholdNight] TransitionTo(YellowOn)
    if (light < thresholdNight)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTYELLOW_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `YellowOn`.
        YELLOWON_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightYellow
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state YELLOWOFF
////////////////////////////////////////////////////////////////////////////////

static void YELLOWOFF_enter(MyTraffic* sm)
{
    sm->state_id = MyTraffic_StateId_YELLOWOFF;
    
    // YellowOff behavior
    // uml: enter / { turnOffYellowLight(), timer = 0 }
    {
        // Step 1: execute action `turnOffYellowLight(), timer = 0`
        turnOffYellowLight(), timer = 0;
    } // end of behavior for YellowOff
}

static void YELLOWOFF_exit(MyTraffic* sm)
{
    sm->state_id = MyTraffic_StateId_ROOT;
}

static void YELLOWOFF_tick(MyTraffic* sm)
{
    // YellowOff behavior
    // uml: tick / { timer++ }
    {
        // Step 1: execute action `timer++`
        timer++;
    } // end of behavior for YellowOff
    
    // YellowOff behavior
    // uml: tick [timer >= 1000] TransitionTo(YellowOn)
    if (timer >= 1000)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        YELLOWOFF_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `YellowOn`.
        YELLOWON_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for YellowOff
    
    // YellowOff behavior
    // uml: tick [light >= thresholdNight] TransitionTo(TrafficLightStateRed)
    if (light >= thresholdNight)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        YELLOWOFF_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightStateRed`.
        TRAFFICLIGHTSTATERED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for YellowOff
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state YELLOWON
////////////////////////////////////////////////////////////////////////////////

static void YELLOWON_enter(MyTraffic* sm)
{
    sm->state_id = MyTraffic_StateId_YELLOWON;
    
    // YellowOn behavior
    // uml: enter / { turnOnYellowLight(), timer = 0 }
    {
        // Step 1: execute action `turnOnYellowLight(), timer = 0`
        turnOnYellowLight(), timer = 0;
    } // end of behavior for YellowOn
}

static void YELLOWON_exit(MyTraffic* sm)
{
    // YellowOn behavior
    // uml: exit / { turnOffYellowLight() }
    {
        // Step 1: execute action `turnOffYellowLight()`
        turnOffYellowLight();
    } // end of behavior for YellowOn
    
    sm->state_id = MyTraffic_StateId_ROOT;
}

static void YELLOWON_tick(MyTraffic* sm)
{
    // YellowOn behavior
    // uml: tick / { timer++ }
    {
        // Step 1: execute action `timer++`
        timer++;
    } // end of behavior for YellowOn
    
    // YellowOn behavior
    // uml: tick [light >= thresholdNight] TransitionTo(TrafficLightStateRed)
    if (light >= thresholdNight)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        YELLOWON_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightStateRed`.
        TRAFFICLIGHTSTATERED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for YellowOn
    
    // YellowOn behavior
    // uml: tick [timer >= 1000] TransitionTo(YellowOff)
    if (timer >= 1000)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        YELLOWON_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `YellowOff`.
        YELLOWOFF_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for YellowOn
    
    // No ancestor handles this event.
}

// Thread safe.
char const * MyTraffic_state_id_to_string(MyTraffic_StateId id)
{
    switch (id)
    {
        case MyTraffic_StateId_ROOT: return "ROOT";
        case MyTraffic_StateId_TRAFFICLIGHTGREEN: return "TRAFFICLIGHTGREEN";
        case MyTraffic_StateId_TRAFFICLIGHTSTATERED: return "TRAFFICLIGHTSTATERED";
        case MyTraffic_StateId_TRAFFICLIGHTSTATEREDYELLOW: return "TRAFFICLIGHTSTATEREDYELLOW";
        case MyTraffic_StateId_TRAFFICLIGHTYELLOW: return "TRAFFICLIGHTYELLOW";
        case MyTraffic_StateId_YELLOWOFF: return "YELLOWOFF";
        case MyTraffic_StateId_YELLOWON: return "YELLOWON";
        default: return "?";
    }
}

// Thread safe.
char const * MyTraffic_event_id_to_string(MyTraffic_EventId id)
{
    switch (id)
    {
        case MyTraffic_EventId_REQUESTGREEN: return "REQUESTGREEN";
        case MyTraffic_EventId_TICK: return "TICK";
        default: return "?";
    }
}
